os: linux
  - ubuntu:16.04
  
sudo: required
dist: trusty
language: generic
compiler:
  - clang
  - gcc
# script: "./.travis/build"
before_install:
# install ros
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
  - sudo apt-get update
  - sudo apt-get install ros-indigo-desktop-full
  - sudo rosdep init
  - rosdep update
  
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtinyxml-dev
  - sudo apt-get install -y python
# install librealsense
  - git clone https://github.com/IntelRealSense/librealsense.git
  - cd librealsense
  - git checkout v2.8.1
  - sudo apt-get install -y --install-recommends linux-generic-lts-xenial xserver-xorg-core-lts-xenial xserver-xorg-lts-xenial xserver-xorg-video-all-lts-xenial xserver-xorg-input-all-lts-xenial libwayland-egl1-mesa-lts-xenial
  - sudo apt-get install -y libusb-1.0-0-dev pkg-config libgtk-3-dev
  - ./scripts/install_glfw3.sh
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-5 g++-5
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
  - sudo update-alternatives --set gcc "/usr/bin/gcc-5"
  - mkdir build && cd build
  - cmake ../
  - sudo make uninstall && make clean && make && sudo make install
  - mkdir -p /etc/udev/rules.d/
  - sudo cp config/99-realsense-libusb.rules /etc/udev/rules.d/
  - sudo udevadm control --reload-rules && udevadm trigger
  - sudo apt-get install libssl-dev
  
 # install realsense
  - mkdir -p ~/catkin_ws/src 
  - cd ~/catkin_ws/src
  - git clone https://github.com/intel-ros/realsense.git
  - cd realsense
  - git checkout 2.0.1
  - cd ~/catkin_ws/
  - . /opt/ros/indigo/setup.sh
  - catkin_make
matrix:
  allow_failures:
    - compiler: clang
