sudo: required
dist: xenial
language: generic
compiler:
  - clang
  - gcc

before_install:
# Building from source ros2
  - sudo locale-gen en_US en_US.UTF-8
  - sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - wget http://registrationcenter-download.intel.com/akdlm/irc_nas/15078/l_openvino_toolkit_p_2018.5.455.tgz 
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys 421C365BD9FF1F717815A3895523BAEEB01FA116
  - sudo apt update
  - sudo apt install git wget
  - sudo apt install build-essential cppcheck cmake libopencv-dev python-empy python3-catkin-pkg-modules python3-dev python3-empy python3-nose python3-pip python3-pyparsing python3-setuptools python3-vcstool python3-yaml libtinyxml-dev libeigen3-dev libassimp-dev libpoco-dev
  - sudo -H python3 -m pip install -U setuptools
  - sudo apt install python3-colcon-common-extensions
  - sudo apt install clang-format pydocstyle pyflakes python3-coverage python3-mock python3-pep8 uncrustify
  - sudo -H python3 -m pip install argcomplete
  - sudo -H python3 -m pip install flake8 flake8-blind-except flake8-builtins flake8-class-newline flake8-comprehensions flake8-deprecated flake8-docstrings flake8-import-order flake8-quotes
  - sudo -H python3 -m pip install pytest pytest-cov pytest-runner
  - sudo -H python3 -m pip install pytest-repeat pytest-rerunfailures
  - sudo apt install libasio-dev libtinyxml2-dev
  - sudo apt install libexpat1-dev libpcre3-dev libsqlite3-dev zlib1g-dev
  - sudo apt install libcurl4-openssl-dev libfreetype6-dev libgles2-mesa-dev libglu1-mesa-dev libqt5core5a libqt5gui5 libqt5opengl5 libqt5widgets5 libxaw7-dev libxrandr-dev qtbase5-dev
  
  # Get ROS 2.0 code
  - mkdir -p ~/ros2_ws/src
  - cd ~/ros2_ws
  - wget https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
  - vcs-import src < ros2.repos
  
  # build 
  - colcon build --symlink-install
   
# install librealsense
  - git clone https://github.com/IntelRealSense/librealsense.git
  - cd librealsense
  - git checkout v2.8.1
  - sudo apt-get install -y libusb-1.0-0-dev pkg-config libgtk-3-dev
  - sudo apt-get install libglfw3-dev
  - mkdir build && cd build
  - cmake ../
  - sudo make uninstall && make clean && make && sudo make install
  - mkdir -p /etc/udev/rules.d/
  - sudo cp ../config/99-realsense-libusb.rules /etc/udev/rules.d/
  - sudo udevadm control --reload-rules && udevadm trigger
  - sudo apt-get install libssl-dev
  
 # install realsense
  - mkdir -p ~/catkin_ws/src 
  - cd ~/catkin_ws/src
  - git clone https://github.com/intel-ros/realsense.git
  - cd realsense
  - git checkout 2.0.1
  - cd ~/catkin_ws/
  - . /opt/ros/kinetic/setup.sh
  - catkin_make
matrix:
  allow_failures:
    - compiler: clang
