sudo: required
dist: bionic
language: generic
compiler:
  - clang
  - gcc

before_install:
# install ros2_openvino_toolkit deps
  - git clone https://github.com/congliu0913/ros2_openvino_toolkit -b devel
  - src/ros2_openvino_toolkit/script/environment_setup_binary.sh
matrix:
  allow_failures:
    - compiler: clang
