sudo: required
dist: xenial
language: generic
compiler:
  - clang
  - gcc
services:
  - docker
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libtinyxml-dev
  - sudo apt-get install -y python
  - 'sudo docker build --no-cache  --rm --file=docker/Dockerfile --tag=ubuntu:1604 docker'
matrix:
  allow_failures:
    - compiler: clang
